version: '2'
services:
    opengateway-elasticsearch:
        container_name: opengateway-elasticsearch
        image: elasticsearch:2.3.5
        # volumes:
        #     - ~/volumes/jhipster/opengateway/elasticsearch/:/usr/share/elasticsearch/data/
        ports:
            - 9200:9200
            - 9300:9300
