version: '2'
services:
    opengateway-mysql:
        container_name: opengateway-mysql
        image: mysql:5.7.14
        # volumes:
        #     - ~/volumes/jhipster/opengateway/mysql/:/var/lib/mysql/
        environment:
            - MYSQL_USER=root
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
            - MYSQL_DATABASE=opengateway
        ports:
            - 3306:3306
        command: mysqld --lower_case_table_names=1 --skip-ssl
